### ISSUE TITLE
Badge details

### ISSUE THREAD

**Issue by tacotexmex** [dolanmiu/Minetest-Texture-Pack-Completion-Checker#2]
I suggest that badges grab the naming from the mod repo name like this:
`https://img.shields.io/badge/<MODREPO>-<PERCENTAGE>-<COLOR>.svg`

This with an extra check to omit eventual "minetest-" and "minetest-mod-" prefixes. That would produce a badge looking like: ![](https://img.shields.io/badge/farming-25%25-red.svg)

(and never display badges looking like: ![](https://img.shields.io/badge/minetest%E2%80%93moddymod-75%25-yellow.svg) )

I also suggest color ranges connected to the percentage variable like this:

![](https://img.shields.io/badge/farming-0%25-lightgray.svg) 0-19
![](https://img.shields.io/badge/farming-20%25-red.svg) 20-39
![](https://img.shields.io/badge/farming-40%25-orange.svg) 40-59
![](https://img.shields.io/badge/farming-60%25-yellow.svg) 60-79
![](https://img.shields.io/badge/farming-80%25-yellowgreen.svg) 80-89
![](https://img.shields.io/badge/farming-90%25-green.svg) 90-94
![](https://img.shields.io/badge/farming-95%25-brightgreen.svg) 95-100

The reason the threshold values would grow exponential-like is that brightgreen level more or less guarantees an overhaul look because than 5% non-coverage is likely to ruin the look (it only takes a few non-themed blocks to break a certain look). 🙂 

![image](https://cloud.githubusercontent.com/assets/25328789/25616738/cba6a87a-2f3e-11e7-9ef5-b69284304da8.png)

**Comment by dolanmiu** [comment]
Great suggestion! I will work on this on the weekend

**Comment by tacotexmex** [comment]
Awesome!

**Comment by dolanmiu** [comment]
Done this :)

Added color, and name of the mod, and truncated the `minetest-` prefix if any exists

**Comment by tacotexmex** [comment]
Cool!
