### ISSUE TITLE
"404 badge not found"

### ISSUE THREAD

**Issue by tacotexmex** [dolanmiu/Minetest-Texture-Pack-Completion-Checker#3]
I'll write this bug up here as well so it's not forgotten.

When mod support is looked up dynamically via
`http://minetest-checker.herokuapp.com/mod/minetest-mods/moreores/minetest-texturepacks/Good-Morning-Craft-Minetest`

the JSON output looks good.

However, when trying to render an SVG the same way,
`http://minetest-checker.herokuapp.com/mod/minetest-mods/moreores/minetest-texturepacks/Good-Morning-Craft-Minetest.svg`,

the output is a 404 badge 
![image](https://cloud.githubusercontent.com/assets/25328789/25693987/7cc50890-30ac-11e7-86ff-699082987d14.png)

**Comment by dolanmiu** [comment]
Fixed:

https://minetest-checker.herokuapp.com/mod/tenplus1/farming/minetest-texturepacks/Good-Morning-Craft-Minetest.svg

**Comment by tacotexmex** [comment]
Great!
